name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install javascript dependencies
      run: npm install
    - name: create android project
      run: npx expo prebuild -p android
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./android
    - name: Build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: android/app/build
